/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package papeleria.view;

import controller.FRAMEApartarController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import papeleria.model.Apartado;
import papeleria.model.Cliente;
import papeleria.model.TableBaseDAO;

/**
 *
 * @author heber
 */
public class Apartar extends javax.swing.JFrame {

    /**
     * Creates new form Apartar
     */
    private static Cliente cliente;
    private static Apartado apartado;
    private static int index[];
    private static List<JTable> tablas;
    private static Apartar gui;
    private static boolean abonar;
    private static List<JButton> botones;
    private static boolean editar;

    public Apartar(Cliente cliente, Apartado apartado, int[] index, List<JTable> tablas, boolean abonar, List<JButton> botones, boolean editar) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        this.apartado = apartado;
        this.index = index;
        this.tablas = tablas;
        this.abonar = abonar;
        this.botones = botones;
        this.editar = editar;
        cargarControladorYEventos();
    }

    private void cargarControladorYEventos() {
        JTextField textFields[] = new JTextField[5];
        textFields[0] = txtNombre;
        textFields[1] = txtApellido;
        textFields[2] = txtTelefono;
        textFields[3] = txtTotal;
        textFields[4] = txtAbono;

        JLabel[] labels = new JLabel[4];
        labels[0] = lblAbono;
        labels[1] = lblAPagar;
        labels[2] = lblPagado;
        labels[3] = lblFechaMaxima;

        List<JPanel> modificadores = new ArrayList();
        modificadores.add(btnMenuMinimizar);
        modificadores.add(btnMenuCerrar);
        modificadores.add(toGrab);

        JButton[] buttons = new JButton[4];
        buttons[0] = btnAbonar;
        buttons[1] = btnApartar;
        try {
            buttons[2] = botones.get(0);
            buttons[3] = botones.get(1);
        } catch (java.lang.NullPointerException ex) {
            //ex.printStackTrace();
        }

        FRAMEApartarController controller = new FRAMEApartarController(cliente, apartado, textFields, labels, modificadores, this, txtaDescripcion, cbxConcepto, abonar, buttons, tablas, index, editar);

        btnAbonar.addActionListener(controller);
        btnApartar.addActionListener(controller);
        toGrab.addMouseListener(controller);
        toGrab.addMouseMotionListener(controller);
        btnMenuCerrar.addMouseListener(controller);
        btnMenuMinimizar.addMouseListener(controller);

    }

    public static Apartar getInstance(Cliente cliente, Apartado apartado, int index[], List<JTable> tablas, boolean abonar, boolean editar) {
        gui = new Apartar(cliente, apartado, index, tablas, abonar, botones, editar);
        return gui;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxConcepto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblAbono = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        lblAPagar = new javax.swing.JLabel();
        lblPagado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        btnApartar = new javax.swing.JButton();
        lblFechaMaxima = new javax.swing.JLabel();
        btnAbonar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jMenuBarOpciones = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre/s:");

        jLabel2.setText("Teléfono:");

        jLabel3.setText("Concepto:");

        cbxConcepto.setBackground(new java.awt.Color(240, 240, 240));
        cbxConcepto.setForeground(new java.awt.Color(0, 0, 0));
        cbxConcepto.setModel(TableBaseDAO.comboModel("Conceptos"));

        jLabel4.setText("Descripción:");

        jLabel5.setText("Costo:");

        lblAbono.setText("Primer abono:");

        lblAPagar.setText("A pagar:");

        lblPagado.setText("Pagado:");

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setLineWrap(true);
        txtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtaDescripcion);

        btnApartar.setBackground(new java.awt.Color(240, 240, 240));
        btnApartar.setForeground(new java.awt.Color(0, 0, 0));
        btnApartar.setText("Apartar");

        lblFechaMaxima.setText("Fecha máxima:");

        btnAbonar.setBackground(new java.awt.Color(240, 240, 240));
        btnAbonar.setForeground(new java.awt.Color(0, 0, 0));
        btnAbonar.setText("Abonar");

        jLabel6.setText("Apellido/s:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxConcepto, 0, 138, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaMaxima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbonar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApartar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAbono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblAPagar)
                            .addComponent(lblPagado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAbono)
                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAPagar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApartar)
                    .addComponent(lblFechaMaxima)
                    .addComponent(btnAbonar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toGrab = new javax.swing.JPanel();
        btnMenuMinimizar = new javax.swing.JPanel();
        btnMenuCerrar = new javax.swing.JPanel();
        jMenuBarOpciones.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBarOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jMenuBarOpciones.setForeground(new java.awt.Color(153, 153, 153));
        jMenuBarOpciones.setAlignmentY(0.5F);
        jMenuBarOpciones.setBorderPainted(false);
        jMenuBarOpciones.setPreferredSize(new java.awt.Dimension(410, 35));

        toGrab.setBackground(new java.awt.Color(153,153,153));
        toGrab.setPreferredSize(new java.awt.Dimension(300, 35));
        toGrab.setMaximumSize(new java.awt.Dimension(32767, 35));

        title.setSize(80, 35);
        title.setBounds(2, 2, 80, 35);
        title.setForeground(new java.awt.Color(255,255,255));
        toGrab.setLayout(null);

        //jMenuBarOpciones.add(title);
        toGrab.add(title);
        jMenuBarOpciones.add(toGrab);

        setJMenuBar(jMenuBarOpciones);
        btnMenuMinimizar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-icon.png")))); // NOI18N
        btnMenuMinimizar.setBackground(new java.awt.Color(153,153,153));
        btnMenuMinimizar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuMinimizar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuMinimizar);

        jMenuBarOpciones.setMaximumSize(new java.awt.Dimension(0, 0));

        btnMenuCerrar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/close-icon.png")))); // NOI18N
        btnMenuCerrar.setBackground(new java.awt.Color(153,153,153));
        btnMenuCerrar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuCerrar.setMaximumSize(new java.awt.Dimension(45, 35));

        jMenuBarOpciones.add(btnMenuCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JLabel title = new javax.swing.JLabel("");
    private javax.swing.JPanel toGrab;
    private javax.swing.JPanel btnMenuMinimizar;
    private javax.swing.JPanel btnMenuCerrar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnApartar;
    private javax.swing.JComboBox<String> cbxConcepto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBarOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAPagar;
    private javax.swing.JLabel lblAbono;
    private javax.swing.JLabel lblFechaMaxima;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables

}
