/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package papeleria.view;

import controller.OpcionesController;
import controller.FRAMETablaBaseController;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author heber
 */
public class BaseTable extends javax.swing.JFrame {

    /**
     * Creates new form Concepts
     */
    private static BaseTable base;
    private List<JComboBox> combos;
    private JTable tblClientes;
    String titulo;

    public BaseTable(String titulo, List<JComboBox> combos, JTable tblClientes) {
        this.titulo = titulo;
        this.combos = combos;
        this.tblClientes = tblClientes;
        initComponents();
        this.setLocationRelativeTo(this);
        this.title.setText(" " + titulo);
        this.setDefaultCloseOperation(BaseTable.DISPOSE_ON_CLOSE);
        
        if (titulo !="Clientes") {
            setVisibleTelefono(false);
        }else{
            setVisibleTelefono(true);
        }
        
        cargarControladorYEventos();
    }
    
    public BaseTable(){
        
    }

    private void cargarControladorYEventos() {
        List<Component> componentes = new ArrayList();
        componentes.add(tblConcepts);
        componentes.add(cbxFiltro);
        componentes.add(txtName);
        componentes.add(btnAdd);
        componentes.add(btnDelete);
        componentes.add(btnRestaurar);
        componentes.add(txtApellido);
        componentes.add(txtTelefono);
        
        List<JPanel> modificadores = new ArrayList();
        modificadores.add(btnMenuMinimizar);
        modificadores.add(btnMenuCerrar);
        modificadores.add(toGrab);

        FRAMETablaBaseController controller = new FRAMETablaBaseController(componentes, titulo, combos, this, modificadores, tblClientes);
        tblConcepts.addMouseListener(controller);
        cbxFiltro.addActionListener(controller);

        btnAdd.addActionListener(controller);
        btnDelete.addActionListener(controller);
        btnRestaurar.addActionListener(controller);
        toGrab.addMouseListener(controller);
        toGrab.addMouseMotionListener(controller);
        btnMenuCerrar.addMouseListener(controller);
        btnMenuMinimizar.addMouseListener(controller);
        
    }
    
    public void setVisibleTelefono(boolean value){
        this.txtApellido.setVisible(value);
        this.lblApellido.setVisible(value);
        this.txtApellido.setEnabled(value);
        this.lblApellido.setEnabled(value);
        this.txtTelefono.setVisible(value);
        this.lblTelefono.setVisible(value);
        this.txtTelefono.setEnabled(value);
        this.lblTelefono.setEnabled(value);
        this.cbxFiltro.setVisible(!value);
        this.btnDelete.setVisible(!value);
        this.btnRestaurar.setVisible(!value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbxFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConcepts = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jMenuBarOpciones = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        cbxFiltro.setBackground(new java.awt.Color(240, 240, 240));
        cbxFiltro.setForeground(new java.awt.Color(0, 0, 0));
        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrados", "Eliminados", "Todos" }));
        cbxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFiltroActionPerformed(evt);
            }
        });

        tblConcepts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tblConcepts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblConcepts.setRowHeight(30);
        tblConcepts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblConcepts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblConcepts);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setMinimumSize(new java.awt.Dimension(142, 307));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("Nombre: ");

        btnDelete.setBackground(new java.awt.Color(240, 240, 240));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Eliminar");
        btnDelete.setEnabled(false);

        btnAdd.setBackground(new java.awt.Color(240, 240, 240));
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Aceptar");
        btnAdd.setMaximumSize(new java.awt.Dimension(171, 22));
        btnAdd.setMinimumSize(new java.awt.Dimension(171, 22));
        btnAdd.setPreferredSize(new java.awt.Dimension(171, 22));

        btnRestaurar.setBackground(new java.awt.Color(240, 240, 240));
        btnRestaurar.setForeground(new java.awt.Color(0, 0, 0));
        btnRestaurar.setText("Restaurar");
        btnRestaurar.setEnabled(false);

        lblTelefono.setText("Teléfono:");
        lblTelefono.setEnabled(false);

        txtTelefono.setEnabled(false);

        lblApellido.setText("Apellido:");
        lblApellido.setEnabled(false);

        txtApellido.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );

        toGrab = new javax.swing.JPanel();
        btnMenuMinimizar = new javax.swing.JPanel();
        btnMenuCerrar = new javax.swing.JPanel();
        jMenuBarOpciones.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBarOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jMenuBarOpciones.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBarOpciones.setAlignmentY(0.5F);
        jMenuBarOpciones.setBorderPainted(false);
        jMenuBarOpciones.setPreferredSize(new java.awt.Dimension(410, 35));

        toGrab.setBackground(new java.awt.Color(153,153,153));
        toGrab.setPreferredSize(new java.awt.Dimension(410, 35));
        toGrab.setMaximumSize(new java.awt.Dimension(32767, 35));

        title.setSize(80, 35);
        title.setBounds(2, 2, 80, 35);
        title.setForeground(new java.awt.Color(255,255,255));
        toGrab.setLayout(null);

        //jMenuBarOpciones.add(title);
        toGrab.add(title);
        jMenuBarOpciones.add(toGrab);

        setJMenuBar(jMenuBarOpciones);
        btnMenuMinimizar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-icon.png")))); // NOI18N
        btnMenuMinimizar.setBackground(new java.awt.Color(153,153,153));
        btnMenuMinimizar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuMinimizar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuMinimizar);

        jMenuBarOpciones.setMaximumSize(new java.awt.Dimension(0, 0));

        btnMenuCerrar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/close-icon.png")))); // NOI18N
        btnMenuCerrar.setBackground(new java.awt.Color(153,153,153));
        btnMenuCerrar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuCerrar.setMaximumSize(new java.awt.Dimension(45, 35));

        jMenuBarOpciones.add(btnMenuCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFiltroActionPerformed

    public static BaseTable getInstance(String titulo, List<JComboBox> combos, JTable tblClientes) {
        base = new BaseTable(titulo, combos, tblClientes);
        return base;
    }
    private javax.swing.JLabel title = new javax.swing.JLabel("");
    private javax.swing.JPanel toGrab;
    private javax.swing.JPanel btnMenuMinimizar;
    private javax.swing.JPanel btnMenuCerrar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBarOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblConcepts;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
