/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package papeleria.view;

import controller.FRAMEExportController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import papeleria.model.TableBaseDAO;
import papeleria.model.VentaDAO;

/**
 *
 * @author heber
 */
public class Export extends javax.swing.JFrame {

    /**
     * Creates new form Export
     */

    public Export() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(BaseTable.DISPOSE_ON_CLOSE);


        List<JComboBox> combos = new ArrayList();
        combos.add(cbxConcepto);
        combos.add(cbxInicialYear);
        combos.add(cbxInicialMonth);
        combos.add(cbxInicialDay);
        combos.add(cbxFinalYear);
        combos.add(cbxFinalMonth);
        combos.add(cbxFinalDay);

        List<JPanel> modificadores = new ArrayList();
        modificadores.add(btnMenuMinimizar);
        modificadores.add(btnMenuCerrar);
        modificadores.add(toGrab);
        
        List<JRadioButton> radioButtons =  new ArrayList();
        radioButtons.add(rbtnMensual);
        radioButtons.add(rbtnIntervalo);
        
        
        FRAMEExportController controller = new FRAMEExportController(combos, this, modificadores, btnExport, radioButtons);
        cbxInicialYear.addActionListener(controller);
        cbxInicialMonth.addActionListener(controller);
        cbxInicialDay.addActionListener(controller);
        cbxFinalYear.addActionListener(controller);
        cbxFinalMonth.addActionListener(controller);
        cbxFinalDay.addActionListener(controller);
        toGrab.addMouseListener(controller);
        toGrab.addMouseMotionListener(controller);
        btnMenuCerrar.addMouseListener(controller);
        btnMenuMinimizar.addMouseListener(controller);
        btnExport.addActionListener(controller);
        rbtnMensual.addActionListener(controller);
        rbtnIntervalo.addActionListener(controller);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modoExportar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbxConcepto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxInicialYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxInicialMonth = new javax.swing.JComboBox<>();
        btnExport = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxFinalDay = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxFinalMonth = new javax.swing.JComboBox<>();
        cbxFinalYear = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxInicialDay = new javax.swing.JComboBox<>();
        rbtnIntervalo = new javax.swing.JRadioButton();
        rbtnMensual = new javax.swing.JRadioButton();
        jMenuBarOpciones = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxConcepto.setBackground(new java.awt.Color(240, 240, 240));
        cbxConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxConcepto.setForeground(new java.awt.Color(0, 0, 0));
        cbxConcepto.setModel(TableBaseDAO.comboModelTodo("Conceptos"));
        jPanel1.add(cbxConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona los datos a exportar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registros con concepto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha Final");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        cbxInicialYear.setBackground(new java.awt.Color(240, 240, 240));
        cbxInicialYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxInicialYear.setForeground(new java.awt.Color(0, 0, 0));
        cbxInicialYear.setModel(VentaDAO.comboModelAño());
        jPanel1.add(cbxInicialYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        cbxInicialMonth.setBackground(new java.awt.Color(240, 240, 240));
        cbxInicialMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxInicialMonth.setForeground(new java.awt.Color(0, 0, 0));
        cbxInicialMonth.setModel(VentaDAO.comboModelMeses(cbxInicialYear));
        jPanel1.add(cbxInicialMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        btnExport.setBackground(new java.awt.Color(245, 245, 245));
        btnExport.setForeground(new java.awt.Color(0, 0, 0));
        btnExport.setText("Exportar");
        jPanel1.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Día:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        cbxFinalDay.setBackground(new java.awt.Color(240, 240, 240));
        cbxFinalDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFinalDay.setForeground(new java.awt.Color(0, 0, 0));
        cbxFinalDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxFinalDay.setEnabled(false);
        jPanel1.add(cbxFinalDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Día:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mes:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        cbxFinalMonth.setBackground(new java.awt.Color(240, 240, 240));
        cbxFinalMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFinalMonth.setForeground(new java.awt.Color(0, 0, 0));
        cbxFinalMonth.setModel(VentaDAO.comboModelMeses(cbxInicialYear));
        cbxFinalMonth.setEnabled(false);
        jPanel1.add(cbxFinalMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        cbxFinalYear.setBackground(new java.awt.Color(240, 240, 240));
        cbxFinalYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFinalYear.setForeground(new java.awt.Color(0, 0, 0));
        cbxFinalYear.setModel(VentaDAO.comboModelAño());
        cbxFinalYear.setEnabled(false);
        jPanel1.add(cbxFinalYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Año:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Año:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha Inicial");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        cbxInicialDay.setBackground(new java.awt.Color(240, 240, 240));
        cbxInicialDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxInicialDay.setForeground(new java.awt.Color(0, 0, 0));
        cbxInicialDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxInicialDay.setEnabled(false);
        jPanel1.add(cbxInicialDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        rbtnIntervalo.setBackground(new java.awt.Color(245, 245, 245));
        modoExportar.add(rbtnIntervalo);
        rbtnIntervalo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnIntervalo.setText("Intervalo de Fechas");
        rbtnIntervalo.setBorder(null);
        jPanel1.add(rbtnIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        rbtnMensual.setBackground(new java.awt.Color(245, 245, 245));
        modoExportar.add(rbtnMensual);
        rbtnMensual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnMensual.setSelected(true);
        rbtnMensual.setText("Informe Mensual");
        rbtnMensual.setBorder(null);
        jPanel1.add(rbtnMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        toGrab = new javax.swing.JPanel();
        btnMenuMinimizar = new javax.swing.JPanel();
        btnMenuCerrar = new javax.swing.JPanel();
        jMenuBarOpciones.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBarOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jMenuBarOpciones.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBarOpciones.setAlignmentY(0.5F);
        jMenuBarOpciones.setBorderPainted(false);
        jMenuBarOpciones.setPreferredSize(new java.awt.Dimension(410, 35));

        toGrab.setBackground(new java.awt.Color(153,153,153));
        toGrab.setPreferredSize(new java.awt.Dimension(410, 35));
        toGrab.setMaximumSize(new java.awt.Dimension(32767, 35));
        jMenuBarOpciones.add(toGrab);

        setJMenuBar(jMenuBarOpciones);
        btnMenuMinimizar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-icon.png")))); // NOI18N
        btnMenuMinimizar.setBackground(new java.awt.Color(153,153,153));
        btnMenuMinimizar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuMinimizar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuMinimizar);

        jMenuBarOpciones.setMaximumSize(new java.awt.Dimension(0, 0));

        btnMenuCerrar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/close-icon.png")))); // NOI18N
        btnMenuCerrar.setBackground(new java.awt.Color(153,153,153));
        btnMenuCerrar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuCerrar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel toGrab;
    private javax.swing.JPanel btnMenuMinimizar;
    private javax.swing.JPanel btnMenuCerrar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox<String> cbxConcepto;
    private javax.swing.JComboBox<String> cbxFinalDay;
    private javax.swing.JComboBox<String> cbxFinalMonth;
    private javax.swing.JComboBox<String> cbxFinalYear;
    private javax.swing.JComboBox<String> cbxInicialDay;
    private javax.swing.JComboBox<String> cbxInicialMonth;
    private javax.swing.JComboBox<String> cbxInicialYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBarOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup modoExportar;
    private javax.swing.JRadioButton rbtnIntervalo;
    private javax.swing.JRadioButton rbtnMensual;
    // End of variables declaration//GEN-END:variables
}
