/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package papeleria.view;

import controller.ExportController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import papeleria.model.TableBaseDAO;
import papeleria.model.VentaDAO;

/**
 *
 * @author heber
 */
public class Export extends javax.swing.JFrame {

    /**
     * Creates new form Export
     */
    
    
    public Export() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(BaseTable.DISPOSE_ON_CLOSE);
        
        List<JComboBox> combos = new ArrayList();
        combos.add(cbxConcepto);
        combos.add(cbxYear);
        combos.add(cbxMonth);
        
        List<JPanel> modificadores = new ArrayList();
        modificadores.add(btnMenuMinimizar);
        modificadores.add(btnMenuCerrar);
        modificadores.add(toGrab);
        
        ExportController controller = new ExportController(combos, this ,modificadores);
        cbxYear.addActionListener(controller);
        toGrab.addMouseListener(controller);
        toGrab.addMouseMotionListener(controller);
        btnMenuCerrar.addMouseListener(controller);
        btnMenuMinimizar.addMouseListener(controller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxConcepto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxMonth = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMenuBarOpciones = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxConcepto.setBackground(new java.awt.Color(240, 240, 240));
        cbxConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxConcepto.setForeground(new java.awt.Color(0, 0, 0));
        cbxConcepto.setModel(TableBaseDAO.comboModelTodo("Conceptos"));
        jPanel1.add(cbxConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona los datos a exportar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registros con concepto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        cbxYear.setBackground(new java.awt.Color(240, 240, 240));
        cbxYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxYear.setForeground(new java.awt.Color(0, 0, 0));
        cbxYear.setModel(VentaDAO.comboModelAño());
        jPanel1.add(cbxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        cbxMonth.setBackground(new java.awt.Color(240, 240, 240));
        cbxMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMonth.setForeground(new java.awt.Color(0, 0, 0));
        cbxMonth.setModel(VentaDAO.comboModelMeses(cbxYear));
        jPanel1.add(cbxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(245, 245, 245));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Exportar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        toGrab = new javax.swing.JPanel();
        btnMenuMinimizar = new javax.swing.JPanel();
        btnMenuCerrar = new javax.swing.JPanel();
        jMenuBarOpciones.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBarOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jMenuBarOpciones.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBarOpciones.setAlignmentY(0.5F);
        jMenuBarOpciones.setBorderPainted(false);
        jMenuBarOpciones.setPreferredSize(new java.awt.Dimension(410, 35));

        toGrab.setBackground(new java.awt.Color(153,153,153));
        toGrab.setPreferredSize(new java.awt.Dimension(410, 35));
        toGrab.setMaximumSize(new java.awt.Dimension(32767, 35));
        jMenuBarOpciones.add(toGrab);

        setJMenuBar(jMenuBarOpciones);
        btnMenuMinimizar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/minimize-icon.png")))); // NOI18N
        btnMenuMinimizar.setBackground(new java.awt.Color(153,153,153));
        btnMenuMinimizar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuMinimizar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuMinimizar);

        jMenuBarOpciones.setMaximumSize(new java.awt.Dimension(0, 0));

        btnMenuCerrar.add(new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/images/close-icon.png")))); // NOI18N
        btnMenuCerrar.setBackground(new java.awt.Color(153,153,153));
        btnMenuCerrar.setPreferredSize(new java.awt.Dimension(45, 35));
        btnMenuCerrar.setMaximumSize(new java.awt.Dimension(45, 35));
        jMenuBarOpciones.add(btnMenuCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel toGrab;
    private javax.swing.JPanel btnMenuMinimizar;
    private javax.swing.JPanel btnMenuCerrar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxConcepto;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBarOpciones;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
